spring.application.name=ucmp-backend

server.port=8081
# PostgreSQL Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/ucmpdb
#spring.datasource.username=ucmpuser
#spring.datasource.password=securepassword
#spring.datasource.driver-class-name=org.postgresql.Driver

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ucmpdb}
spring.datasource.username=${DB_USERNAME:ucmpuser}
spring.datasource.password=${DB_PASSWORD:securepassword}
spring.datasource.driver-class-name=org.postgresql.Driver

# Give the serverless instance enough time to initialize
spring.datasource.hikari.connection-timeout=45000
spring.datasource.hikari.validation-timeout=15000

# Increase the pool limit so internal schema migrations don't deadlock
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# Balance the driver timeout settings (Match your network transit time)
#spring.datasource.url=jdbc:postgresql://ep-damp-sound-a13jdu4l.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&connectTimeout=30&socketTimeout=60
# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:false}

# Database Initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Disable H2
spring.h2.console.enabled=false

# Security
spring.security.user.name=admin
spring.security.user.password=temp
#jwt settings
jwt.secret=${JWT_SECRET:aVeryLongAndSecureSecretKeyForYourJWTs1234567890abcdef}
jwt.expiration=${JWT_EXPIRATION_MS:86400000}

logging.level.org.springframework.web=${SPRING_WEB_LOG_LEVEL:INFO}